### ISSUE TITLE
Upstream?

### ISSUE THREAD

**Issue by LukeAI** [MaxandreOgeret/vcstool2#5]
Nice project! Is contributing upstream not an option over forking?

**Comment by MaxandreOgeret** [comment]
Hey ! Thanks for your issue and message.
I decided to create a new repo because the upstream once doesn't seem to be maintained anymore and PRs haven't been merged.
The original maintainer has also not been active on Github for some time.

**Comment by LukeAI** [comment]
fair enough

**Comment by 130s** [comment]
Package description https://pypi.org/project/vcstool2/#description indeed mentions at the top:

> Vcstool2 is an attempt at continuing the development of [vcstool](https://github.com/dirk-thomas/vcstool) by Dirk Thomas.

Still, it was easy for me to disregard that line and thought vcstool2 is a project from Dirk's upstream. Maybe add a new section at the top of project desc.

**Comment by MaxandreOgeret** [comment]
Hey @130s and thanks for reaching out !
The repos readme is used as package description on PyPy. You can see that the line you mention is in the readme here : 

https://github.com/MaxandreOgeret/vcstool2/blob/8f91e28aaba1c1677256a259274cbf98c152e726/README.md?plain=1#L3

The project description also mentions it:
![Screenshot_20230923-163520_Firefox~2](https://github.com/MaxandreOgeret/vcstool2/assets/22786578/02938959-3374-4ebf-bada-9987acf61766)

I thought it was enough. If you think it should be made clearer that it's only a fork, I'm open to it.
