### ISSUE TITLE
git invoked by vcstool2 does not use ~/.git-credentials on GHA

### ISSUE THREAD

**Issue by LukeAI** [MaxandreOgeret/vcstool2#6]
Unfortunately I can't give a reproducible example but maybe you have some insight or suggestion or maybe it really is a bug?

I have several private repository dependencies that are pulled together by vcstool for CI tests on Github Actions.

Like this:
```
# configure my git credentials
git config --global credential.helper store
echo "https://${USER}:${MY_GITHUB_PAT}@github.com" > ~/.git-credentials

# test that "git clone" can successfully clone private repos 
git clone https://github.com/MYORG/MYREPO.git/
ls MYREPO

# install vcs and try importing myrepos.repos...
pip3 install vcstool2 --no-deps
vcs import --shallow --debug --input myrepos.repos
```

Just directly running `git clone` works as expected, my private repo is cloned and I can see the expected content with `ls MYREPO`. but trying to clone the same repo, via `vcs import` fails with:

```
=== ./src/myrepo (git) ===
Could not determine ref type of version: remote: Repository not found.
fatal: repository 'https://github.com/MYORG/MYREPO/' not found
```
Behaviour is identical with `vcstool` and `vcstool2`, so for some reason, git correctly finds and uses `~/.git-credentials` when ran directly but when ran by vcstool it doesn't.

I can't reproduce this behaviour on my PC, but this is how it runs on GHA ubuntu-latest. Do you have any insights or ideas?

**Comment by MaxandreOgeret** [comment]
Thanks for opening the issue and using vcstool2,
I will investigate and come back to you if I have questions.

**Comment by LukeAI** [comment]
Thanks for investigating! It's unfortunate that there is no simple way for one private repo to clone another in the same org and for it to "just work". What I'm doing here (in case it wasn't clear) is using a github PAT, stored as a repository secret, made available to the workflow as an environment variable `MY_GITHUB_PAT`

**Comment by MaxandreOgeret** [comment]
Vcstool uses the git client directly to clone the repos. See:
https://github.com/MaxandreOgeret/vcstool2/blob/8f91e28aaba1c1677256a259274cbf98c152e726/vcstool2/clients/git.py#L394

So, I would expect git to work in roughly the same way if it is invoked by the command line or by vcstool. I have just tried locally and vcstool was able to use the credentials to clone a repository.

Could it be that the environment is different when you run vcstool2 ?

**Comment by LukeAI** [comment]
> So, I would expect git to work in roughly the same way if it is invoked by the command line or by vcstool. I have just tried locally and vcstool was able to use the credentials to clone a repository.
yeah I was surprised too. I also could not replicate this behaviour on my local computer

> Could it be that the environment is different when you run vcstool2 ?
It's the same instantiation of the same GHA VM. I suspect that the difference lies in that vcstool directly runs git, (since `shell=false` is the default argument to `Popen` which is ommited). https://github.com/MaxandreOgeret/vcstool2/blob/8f91e28aaba1c1677256a259274cbf98c152e726/vcstool2/clients/vcs_base.py#L69
and the behaviour of git is influenced by shell variables eg. for reading credentials https://git-scm.com/docs/gitcredentials

**Comment by LukeAI** [comment]
I ended up implementing my own "mini-vcstool" which works where vcstool2 doesn't, all it is is:

```
#!/usr/bin/env python3
import os
import yaml
import subprocess

if __name__ == "__main__":
    repos_path = "myrepos.repos"
    root_dir = "."
    root_dir = os.path.abspath(root_dir)
    repos_path = os.path.abspath(repos_path)
    print(root_dir)
    print(repos_path)
    with open(repos_path) as repos_file:
        repos = yaml.safe_load(repos_file)
    for path, remote in repos["repositories"].items():
        cmd = ["/usr/bin/git", "clone", "--depth", "1", "--branch", remote["version"], remote["url"], path]
        print(' '.join(cmd))
        subprocess.Popen(cmd)
```
no idea why this works and vcstool(2) doesn't. the invocation of git seems to be very similar

**Comment by MaxandreOgeret** [comment]
I will close this issue, using `.git-credentials` is not advised, so will not fix.
